plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management'
	id 'io.freefair.lombok'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

springBoot {
	buildInfo()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.fabric8:kubernetes-client:7.5.2'
	implementation 'io.projectreactor:reactor-core'

	implementation 'io.projectreactor:reactor-core-micrometer'
	implementation 'io.micrometer:micrometer-observation'
	implementation 'io.micrometer:micrometer-registry-prometheus'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation "org.testcontainers:testcontainers"
	testImplementation "org.testcontainers:junit-jupiter"
	testImplementation "org.testcontainers:k3s"
	testImplementation 'org.awaitility:awaitility'
	testImplementation 'org.assertj:assertj-core'
}

bootBuildImage {
	def repository = "ghcr.io/xenit-eu/contentgrid-pathfinder"
	imageName = "${repository}:${project.version}"
	tags = "${project.version}".endsWith('SNAPSHOT') ? [ "${repository}:SNAPSHOT" ] : null

	docker {
		publishRegistry {
			url = project.findProperty('DOCKER_PUBLISH_REGISTRY_URL')
			username = project.findProperty('DOCKER_PUBLISH_REGISTRY_USERNAME')
			password = project.findProperty('DOCKER_PUBLISH_REGISTRY_PASSWORD')
		}
	}
}

bootRun {
	args = ["--spring.profiles.active=bootRun"]
}

allprojects {
	pluginManager.withPlugin('java') {
		java {
			toolchain {
				languageVersion = JavaLanguageVersion.of(17)
			}
		}

		tasks.named('test', Test).configure {
			useJUnitPlatform {
				excludeTags('integration')
			}
		}

		tasks.register('integrationTest', Test) {
			useJUnitPlatform {
				includeTags('integration')
			}
			shouldRunAfter test
		}

		tasks.named('check').configure {
			dependsOn 'integrationTest'
		}
	}

	plugins.withType(io.freefair.gradle.plugins.lombok.LombokPlugin).whenPluginAdded { p ->
		lombok {
			version = lombokVersion
		}
	}
}
