logging.level:
  com.contentgrid.pathfinder: DEBUG
management:
  endpoints:
    web:
      exposure.include: health,info,prometheus,metrics

pathfinder:
  source:
    namespace: default
    labels:
      '[app.contentgrid.com/service-type]': gateway
  target:
    namespace: contentgrid-system
    annotations:
      '[cert-manager.io/cluster-issuer]': letsencrypt-production
    services:
      - path: /
        pathType: Prefix
        serviceName: gateway-service
        servicePort: 8080
      - path: /.well-known/jwks.json
        pathType: Exact
        serviceName: slingshot-service
        servicePort: 8080
