logging.level:
  com.contentgrid.pathfinder: DEBUG
management:
  endpoints:
    web:
      exposure.include: health,info,prometheus,metrics

pathfinder:
  source:
    namespace: default
    labels:
      '[app.contentgrid.com/service-type]': gateway
  target:
    namespace: contentgrid-system
